### ISSUE TITLE
'cargo run' fails on clean checkout

### ISSUE THREAD

**Issue by coopernurse** [crazymykl/rust-koans#16]
Thanks for creating these koans.  I'm a rust newb, so this may be user error.  When I try cloning the repo and running `cargo run` I get a compilation error:

```
james ~/src $ git clone https://github.com/crazymykl/rust-koans.git
Cloning into 'rust-koans'...
remote: Counting objects: 150, done.
remote: Total 150 (delta 0), reused 0 (delta 0), pack-reused 150
Receiving objects: 100% (150/150), 26.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (56/56), done.
Checking connectivity... done.

james ~/src $ cd rust-koans/
james ~/src/rust-koans $ cargo run
   Compiling koans v0.2.0 (file:///home/james/src/rust-koans)
src/main.rs:61:5: 61:26 error: file not found for module `path_to_enlightenment`
src/main.rs:61 mod path_to_enlightenment;
                   ^~~~~~~~~~~~~~~~~~~~~
src/main.rs:61:5: 61:26 help: name the file either path_to_enlightenment.rs or path_to_enlightenment/mod.rs inside the directory "src"
Could not compile `koans`.

To learn more, run the command again with --verbose.
```

cargo/rustc versions:

```
james ~/src/rust-koans $ rustc --version
rustc 1.5.0 (3d7cd77e4 2015-12-04)
james ~/src/rust-koans $ cargo --version
cargo 0.6.0-nightly (e1ed995 2015-10-22)
```

I'll poke around and see if I can figure it out, but filing here in case someone else encounters this, or knows a quick fix.

**Comment by corincerami** [comment]
If you create a 'path_to_enlightenment.rs`file in the`src` directory, that should get you going for now. We'll need to fix this so a clean checkout doesn't require that, or put that in the setup of the Readme.

**Comment by coopernurse** [comment]
Ah, thanks.  this works:

```
touch src/path_to_enlightenment.rs
cargo run
```

However, it looks like a new `koan!(...);` line is added to `path_to_enlightenment.rs` each time I invoke `cargo run`, even if the previous koan is not passing.

Is that intentional?

**Comment by corincerami** [comment]
@crazymykl I think you can answer the above question better.
