### ISSUE TITLE
Tests do not appear to occur in a discernable order.

### ISSUE THREAD

**Issue by RomanHargrave** [crazymykl/rust-koans#19]
After completing the second koan in `boolean.rs` errors were being generated for `vector.rs`, `hashmap.rs`, `trait.rs`, etc... Perhaps rather than modifying path_to_enlightenment, all the koans should be added in a specific order and run in that order, stopping at the first failing test. 

This would make it _significantly_ easier to complete.

**Comment by crazymykl** [comment]
It does appear that it does not wait for you to pass one before adding the next; I will look into this further soon.
