### ISSUE TITLE
Unsure about for_loops in array

### ISSUE THREAD

**Issue by oemmerson** [crazymykl/rust-koans#25]
I'm confused about the below test.
There are no underscores to fill in

```
fn for_loops() {
    let arr: [u64; 3] = [1, 2, 3];
    let mut y: u64 = 1;
    for x in &arr {
        assert!(*x == y);
    }
}
```
But the test fails.

I'm unsure how to proceed.

Thanks for you work on this project.

**Comment by crazymykl** [comment]
The simplest solution would be to add a thing inside the loop.
