### ISSUE TITLE
orphan rule and `inheritance` in traits.rs

### ISSUE THREAD

**Issue by thedataking** [crazymykl/rust-koans#28]
The trait inheritance koan requires that we implement `PartialOrd` for `std::collections::HashMap`. That seems to conflict with the orphan rule (source [TRPL 2nd Ed.](https://doc.rust-lang.org/book/second-edition/ch10-02-traits.html)):

> One restriction to note with trait implementations: we may implement a trait on a type as long as either the trait or the type are local to our crate. In other words, we aren't allowed to implement external traits on external types. We can't implement the Display trait on Vec, for example, since both Display and Vec are defined in the standard library. We are allowed to implement standard library traits like Display on a custom type like Tweet as part of our aggregator crate functionality. We could also implement Summarizable on Vec in our aggregator crate, since we've defined Summarizable there. This restriction is part of what's called the orphan rule, which you can look up if you're interested in type theory. Briefly, it's called the orphan rule because the parent type is not present. Without this rule, two crates could implement the same trait for the same type, and the two implementations would conflict: Rust wouldn't know which implementation to use. Because Rust enforces the orphan rule, other people's code can't break your code and vice versa. 

My question is whether there is still a valid solution to this koan for users on rust 1.18.0 or later. Thanks for your work & cheers!

**Comment by crazymykl** [comment]
@chrisccerami, you wrote this one, yeah?

**Comment by corincerami** [comment]
Probs. I can fix it at some point.
