### ISSUE TITLE
Koans not working properly

### ISSUE THREAD

**Issue by niklaslong** [crazymykl/rust-koans#29]
After running `cargo run` on first koan I get this: 
```Rust
compiling koans v0.2.0 (file:///Users/niklas/Documents/Random/rust-koans)
warning: unused macro definition
  --> src/main.rs:25:1
   |
25 | / macro_rules! koan {
26 | |     ($name:expr) => (
27 | |         include!(concat!("koans/", $name, ".rs"));
28 | |     );
29 | | }
   | |_^
   |
   = note: #[warn(unused_macros)] on by default

    Finished dev [unoptimized + debuginfo] target(s) in 0.54 secs
     Running `target/debug/koans`

running 1 test
test path_to_enlightenment::the_truth ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
I have just started learning Rust, but I think this isn't the expected behaviour?
This is with `rustc 1.22.1`

**Comment by crazymykl** [comment]
What directory are you in when you do `cargo run`?

**Comment by niklaslong** [comment]
@crazymykl I'm in the root directory of the repository.

**Comment by crazymykl** [comment]
"No such file or directory" is the error, but I don't know which line is causing it.

Can you try: `RUST_BACKTRACE=1 cargo run`, and see what it says?

**Comment by niklaslong** [comment]
Sure thing, here's the backtrace: 
```
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
  10: <core::result::Result<T, E>>::unwrap
  11: koans::seek_the_path
  12: koans::main
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start
  15: main
```

**Comment by crazymykl** [comment]
Which OS are you on? Can you `ls`/`dir` your `src` directory?

**Comment by niklaslong** [comment]
@crazymykl I'm on macOS High Sierra (10.13.1). Heres the `src` dir: 
```
Macbook-Pro:src niklas$ ls
koans  koans.txt  main.rs  path_to_enlightenment.rs
```

**Comment by crazymykl** [comment]
Interesting, I'm on the same OS. I just nuked my checkout and tried again, and I cannot reproduce. I get:

```
😻  ~/w/rust-koans git:master ❯❯❯ cargo run                                                                                                                                                                                     ✭
   Compiling koans v0.2.1 (file:///Users/mmacdonald/workspace/rust-koans)
    Finished dev [unoptimized + debuginfo] target(s) in 1.35 secs
     Running `target/debug/koans`
error[E0425]: cannot find value `__` in this scope
 --> src/koans/the_truth.rs:3:13
  |
3 |     assert!(__)
  |             ^^ not found in this scope

error: aborting due to previous error


To learn more, run the command again with --verbose.
Meditate on your approach and return. Mountains are merely mountains.
```
which is the expected error.

Can you give me any other relevant info?

**Comment by niklaslong** [comment]
@crazymykl Interesting! So I've reproduced the error on a second machine with a fresh install of Rust. Here are the steps: 
1. `git clone` 
2.  `cd rust-koans`
3. `cargo run` at which point it seems to work fine - I get the expected error
4. Answer `the_truth` Koan with `assert!(true)` 
5. `cargo run` now throws the unexpected error

Note: if I answer `assert!(false)` for the first koan the test fails and I get the expected error.
It seems like the unexpected error is being thrown after the first test passes. I'm assuming this is when the next Koan is supposed to be loaded in?

**Comment by crazymykl** [comment]
Okay. I think I know what's going on, and it's related to changes in cargo. Might have a fix soon.

**Comment by niklaslong** [comment]
@crazymykl Great to hear - thank you very much for your work, it's highly appreciated!

**Comment by crazymykl** [comment]
Works locally now, reopen this if it's not fixed for you.
